Beni\BdthequeBundle\Document\ComicStrip:
    type: document
    repositoryClass: Beni\BdthequeBundle\Repository\ComicStripRepository
    fields:
        id:
            id:  true
        title:
            type: string
        author:
            type: string
        resume:
            type: string
        date:
            type: date
        slug:
            type: string
            length: 128
            gedmo:
                slug:
                separator: -
                style: camel
                fields:
                    - title
    referenceOne:
        series:
            targetDocument: Beni\BdthequeBundle\Document\Series
            cascade: all
            inversedBy: comicStrip
