Beni\BdthequeBundle\Document\ComicStrip:
    type: document
    repositoryClass: Beni\BdthequeBundle\Repository\ComicStripRepository
    fields:
        id:
            id:  true
        ISBN:
            type: string
        title:
            type: string
        editor:
            type: string
        designer:
            type: string
        designer:
            type: string
        scenarist:
            type: string
        resume:
            type: string
        legalDeposit:
            type: date
        tome:
            type: int
        category:
            type: string
        slug:
            type: string
            length: 128
            gedmo:
                slug:
                separator: -
                style: camel
                fields:
                    - title
        created:
            type: date
    referenceOne:
        series:
            targetDocument: Beni\BdthequeBundle\Document\Series
            cascade: all
            inversedBy: comicStrips
    referenceMany:
        users:
            targetDocument: Beni\UserBundle\Document\User
            cascade: all
            inversedBy: comicStrips
