Beni\BdthequeBundle\Document\Series:
    type: document
    repositoryClass: Beni\BdthequeBundle\Repository\SeriesRepository
    fields:
        id:
            id:  true
        title:
            type: string
        slug:
            type: string
            length: 128
            gedmo:
                slug:
                separator: -
                style: camel
                fields:
                    - title
    referenceMany:
        comicStrips:
            targetDocument: Beni\BdthequeBundle\Document\ComicStrip
            cascade: all
            mappedBy: series
            sort: tome

