Beni\UserBundle\Document\User:
    type: document
    fields:
        id:
            id:  true
    referenceMany:
        comicStrips:
            targetDocument: Beni\BdthequeBundle\Document\ComicStrip
            cascade: all
            mappedBy: users
