language: php

php:
    - 5.3.3

services:
    - mongodb

before_script:
    - composer install --dev
    # compte pour mongoDB
    - mongo bdtheque_database --eval 'db.addUser("travis", "test");'

script:
    # lancement test phpunit
    - phpunit -c app --coverage-text

notifications:
    email:
      - benijaco@gmail.com
