language: php

php:
    - 5.3.3

services:
    - mongodb

before_script:
    # Fix travis by installing mongo php ext
    - pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    # compte pour mongoDB
    - sleep 15
    - mongo bdtheque_database --eval 'db.addUser("travis", "test");'
    # installation des vendor via composer
    - composer install --dev

script:
    # lancement test phpunit
    - phpunit -c app --coverage-text

after_script:
    # lancement test SensioLabs Insight
    #- 'curl -X POST -H "Accept: application/vnd.com.sensiolabs.insight+xml" "https://56d75495-85ba-4894-9cd6-1033c25cc168:8bf2365488e3324ad8405b43b414c6571a608bf1ea10c3440e137c06a55c0792@insight.sensiolabs.com/api/projects/94ad6866-a596-4429-8bef-759b7933c7c2/analyses"'

notifications:
    email:
      - benijaco@gmail.com
