security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
      # firewall permettant l'accès à la barre de dev
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            form_login:
                login_path:  /user/login
                check_path:  /user/login_check

    access_control:
        # Homepage
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # User
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # Admin
        - { path: ^/admin/, role: ROLE_ADMIN }
        # Bdtheque
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY  }
